cmake_minimum_required(VERSION 3.16)
project(rck C)

include(CheckCSourceCompiles)
include(CMakePushCheckState)
include(GNUInstallDirs)
include(GenerateExportHeader)

option(BUILD_SHARED_LIBS "Build as a shared library" TRUE)
option(BUILD_EXAMPLES "Build examples" TRUE)

find_package(PkgConfig REQUIRED)
set(PC_DEPS_LIST nspr plutosvg ini_config libmagic pixman-1 spng dbus-1)
pkg_check_modules(PC_DEPS REQUIRED IMPORTED_TARGET ${PC_DEPS_LIST})
find_package(X11 REQUIRED COMPONENTS Xext)
cmake_push_check_state(RESET)
set(src_roundf_test "#include <math.h>\nint main(int argc){return roundf(0.4f * (float)argc);}\n")
check_c_source_compiles("${src_roundf_test}" LIBC_HAS_ROUNDF)
if(NOT LIBC_HAS_ROUNDF)
    set(CMAKE_REQUIRED_LIBRARIES "m")
    check_c_source_compiles("${src_roundf_test}" LIBM_HAS_ROUNDF)
endif()
cmake_pop_check_state(RESET)

file(READ "${CMAKE_CURRENT_SOURCE_DIR}/include/rck.h" RCKHDR)
string(REGEX MATCH "RCK_MAJOR_VERSION ([0-9]*)" _ ${RCKHDR})
set(VERSION_MAJOR ${CMAKE_MATCH_1})
string(REGEX MATCH "RCK_MINOR_VERSION ([0-9]*)" _ ${RCKHDR})
set(VERSION_MINOR ${CMAKE_MATCH_1})

file(GLOB_RECURSE SOURCE_FILES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.c")
add_library(librck ${SOURCE_FILES})
generate_export_header(librck BASE_NAME "rck" EXPORT_FILE_NAME "rckexport.h")
add_library(rck::librck ALIAS librck)
set_property(TARGET librck PROPERTY OUTPUT_NAME "rck")
set_property(TARGET librck PROPERTY C_VISIBILITY_PRESET "hidden")
set_property(TARGET librck PROPERTY POSITION_INDEPENDENT_CODE ON)
set_property(TARGET librck PROPERTY C_STANDARD 99)
set_target_properties(librck PROPERTIES VERSION ${VERSION_MAJOR}.${VERSION_MINOR} SOVERSION ${VERSION_MAJOR})
target_include_directories(librck PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>")
target_include_directories(librck PUBLIC "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>")
target_include_directories(librck PUBLIC "${CMAKE_BINARY_DIR}")
target_link_libraries(librck PUBLIC PkgConfig::PC_DEPS X11::X11 X11::Xext)
if(LIBM_HAS_ROUNDF AND NOT LIBC_HAS_ROUNDF)
    target_link_libraries(librck PRIVATE m)
endif()

string(JOIN " " PC_DEPS_PRIVATE ${PC_DEPS_LIST})
configure_file(rck.pc.in rck.pc @ONLY)

install(FILES "${CMAKE_BINARY_DIR}/rckexport.h" DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")
install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/include/rck.h" DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/rckexport.h" DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/rck.pc" DESTINATION "${CMAKE_INSTALL_LIBDIR}/pkgconfig")
install(TARGETS librck ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}" LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}" RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")

if(BUILD_EXAMPLES)
	file(GLOB_RECURSE EXAMPLE_FILES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/examples/*.c")
	foreach(EXAMPLE_FILE ${EXAMPLE_FILES})
		get_filename_component(EXAMPLE_TARGET ${EXAMPLE_FILE} NAME_WE)
        add_executable(${EXAMPLE_TARGET} ${EXAMPLE_FILE})
        target_link_libraries(${EXAMPLE_TARGET} PRIVATE rck::librck)
	endforeach()
endif()
